module.exports = (sequelize, DataTypes) => {

    const actividades = sequelize.define('actividades', {

        id: {
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER
        },

        modulo: DataTypes.INTEGER,
        semestre: DataTypes.INTEGER,
        fecha: DataTypes.TEXT,
        descripcion: DataTypes.TEXT,
        idtipoac: DataTypes.INTEGER,
        idmat: DataTypes.INTEGER,
        idcarrera: DataTypes.INTEGER,
        idper: DataTypes.INTEGER,
        estado: DataTypes.CHAR(1)

    });


    actividades.associate = function (models) {
        // personas.belongsToMany(models.jurados,{
        //     through: 'personas_id',
        //     foreignKey: 'id',
        //     otherKey: 'id'
        // });
        // personas.hasMany(models.jurados,{
        //     foreignKey: 'id',
        //     sourceKey: 'id'
        // });
        actividades.belongsTo(models.carreras, {
            foreignKey: 'idcarrera',
            targetKey: 'id'
        });
        actividades.belongsTo(models.materias, {
            foreignKey: 'idmat',
            targetKey: 'id'
        });
        actividades.belongsTo(models.tipo_actividades, {
            foreignKey: 'idtipoac',
            targetKey: 'id'
        });
        actividades.belongsTo(models.personas, {
            foreignKey: 'idper',
            targetKey: 'id'
        });
        // pruebas.belongsTo(models.usuarios, {
        //     foreignKey: 'id',
        //     targetKey: 'id'
        //   });
    };


    return actividades;

}



// create table actividades(
//     id int GENERATED by DEFAULT as IDENTITY PRIMARY key,
//       modulo int not null,
//       semestre text not null,
//       fecha date not null,
//       descripcion text not null,
//       idtipoac int REFERENCES tipo_actividades ,
//       idmat int REFERENCES materias ,
//       idcarrera int REFERENCES carreras,
//       idper int REFERENCES personas,
//       estado char(1),
//    "createdAt" date,
//   "updatedAt" date
//    );