module.exports = (sequelize,DataTypes)=>{

    const archivos = sequelize.define('archivos',{

        id:{
            autoIncrement:true,
            primaryKey:true,
            type:DataTypes.INTEGER
        },

        nombre:DataTypes.TEXT,
        estado:DataTypes.CHAR(1),
        idact:DataTypes.INTEGER
    });







    return archivos;
}




// CREATE table archivos(
//     id int GENERATED by DEFAULT as IDENTITY PRIMARY key,
//    nombre text not null,
//    estado char(1),
//    idact int REFERENCES actividades,
//     "createdAt" date,
//    "updatedAt" date
//     );