module.exports = (sequelize,DataTypes)=>{

    const cuentas = sequelize.define('cuentas',{

        id:{
            autoIncrement:true,
            primaryKey:true,
            type:DataTypes.INTEGER
        },

        usuario:DataTypes.TEXT,
        password:DataTypes.TEXT,
        estado:DataTypes.CHAR(1),
        idper: DataTypes.INTEGER
    
    })
    return cuentas;

}

// create table cuentas(
//     id int GENERATED by DEFAULT as IDENTITY PRIMARY key,
//     usuario text not null,
//     password text not null,
//     estado char(1),
//     idper int REFERENCES personas(id),
//     "createdAt" date,
//     "updatedAt" date
//     );
    