module.exports = (sequelize, DataTypes) => {

    const personas = sequelize.define('personas', {

        id: {
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER
        },
        nombres: DataTypes.TEXT,
        apat: DataTypes.TEXT,
        amat: DataTypes.TEXT,
        email: DataTypes.TEXT,
        idrol: DataTypes.INTEGER,
        limitacion: DataTypes.DOUBLE,
        idcarr: DataTypes.INTEGER,
        estado: DataTypes.CHAR(1)
    });
    personas.associate = function (models) {
        personas.hasOne(models.cuentas, {
            foreignKey: 'idper',
            sourceKey: 'id'
        });
        // personas.belongsTo(models.roles, {
        //     foreignKey: 'idrol',
        //     targetKey: 'id'
        // });
    };

    return personas;

};

// CREATE table personas(
//     id int GENERATED by DEFAULT as IDENTITY PRIMARY key,
//     nombres text not null,
//     apat text not null,
//     amat text not null,
//     email text not null,
//     idrol int REFERENCES roles(id),
//     limitacion int not null,
//      char(1),
//     "createdAt" date,
//     "updatedAt" date
//     );