module.exports = (sequelize,DataTypes)=>{

    const roles = sequelize.define('roles',{

        id:{
            autoIncrement:true,
            primaryKey:true,
            type:DataTypes.INTEGER
        },

        nombre:DataTypes.TEXT,
        estado:DataTypes.CHAR(1),
    });
    return roles;
};


// create table roles(
//     id int GENERATED by DEFAULT as IDENTITY PRIMARY key,
//     nombre text not null,
//     estado char(1),
//     "createdAt" date,
//     "updatedAt" date
//     );